### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "0f0c3788477c4c16bdeba77ba069715b",
  "accountNumber": "1000000000",
  "amount": 1000
}

### query transaction
GET http://localhost:8080/transaction/068d2827e4164e05ab1c62f81bcdfcf8
Content-Type: application/json
